data:
  monthly_data_folder: "../data/monthly_p2_readings/"
  combined_output_csv: "../data/Air_Quality_Lagos_Combined.csv"
  resample_freq: "6H"

model:
  type: "SARIMA"
  order: [2, 1, 3]
  seasonal_order: [1, 0, 1, 28]
  seasonal_period: 28

paths:
  results_folder: "../results/"
  models_folder: "../models/"
  combined_csv: "../data/Air_Quality_Lagos_Combined.csv"

validation:
  test_start_date: "2024-11-25"
