data:
  monthly_data_folder: "data/monthly_p2_readings/"
  combined_output_csv: "data/Air_Quality_Lagos_Combined.csv"
  resample_freq: "6H"

model:
  type: "SARIMA"
  order: [3, 1, 1]
  seasonal_order: [2, 0, 2, 4]
  seasonal_period: 4

paths:
  results_folder: "results/"
  models_folder: "models/"
  combined_csv: "data/Air_Quality_Lagos_Combined.csv"

validation:
  test_start_date: "2024-11-25"
